### ISSUE TITLE
ClosePostMessage doesn't show Exit in UI

### ISSUE THREAD

**Issue by tuckdesign** [Microsoft/Office-Online-Test-Tools-and-Documentation#184] opened 2016-03-22 00:31 UTC
Not sure why this happens (is it a bug or something wrong in docs, or I am doing something wrong). 
I am creating new pptx. I use https://wopi.readthedocs.org/en/latest/scenarios/customization.html?highlight=checkfileinfo#postmessage-properties
ClosePostMessage: true,
and PostMessageOrigin: https://<domain>
are sent from host (with other parameters).
In JS I get 'App_LoadingStatus' message from office online iframe and I send 'Host_PostmessageReady' message to it.
Unfortunatelly, 'Exit' under 'File' in editor is grayed out and doesn't work.

Spent a lot of time on experimenting what might be wrong and found out that this is working only if I set CloseUrl in CheckFileInfo to same url as PostMessageOrigin (just https://<domain>). According to docs, setting CloseUrl should reload to page in browser (or change url to CloseUrl URL):
"If provided, when the Close UI is activated, Office Online will navigate the outer page (window.top.location) to the URI provided."
But this doesn't happen. When I send CloseUrl=https://<domain> I then see 'Exit' in UI and I do get 'UI_Close' message in JS on host side. It's ok if it is supposed to work like this, but wouldn't like that after some time clicking 'Exit' starts redirecting users to home page.

**Comment by tylerbutler** [comment] 2016-03-22 15:57
The documentation is unclear here. In order for the Close UI to be operational, `CloseUrl` must always be provided. This is because there are some cases where Office Online uses the `CloseUrl` when it can't (for various reasons) send the `UI_Close` post message. I tested this and saw the expected behavior. I will file a separate issue to update this info in the docs.

If you just specify the `CloseUrl` without setting `ClosePostMessage` to true, then all the apps will navigate to that URL as described in the docs. I tested with both a URL that was within the same domain as the `PostMessageOrigin` and an absolute URL that was completely external and both have the same behavior.

By the way, I don't think your `PostMessageOrigin` is correct, @tuckdesign. It should be the domain of your host page. However you're receiving the messages, so maybe this isn't an issue. It will probably cause some problems, though, so I suggest you provide an actual domain along with the protocol.

**Comment by tylerbutler** [comment] 2016-03-22 15:57
Filed #85 to track updating the `CloseUrl` and `ClosePostMessage` docs.

**Comment by tuckdesign** [comment] 2016-03-22 16:26
@tylerbutler 
Thx for response. PostMessageOrigin is ok and it works fine (when CloseUrl is set). Haven't noticed that in my first post https://&lt;domain&gt; became just https:// (guess because of markdown)

**Comment by tylerbutler** [comment] 2016-03-27 16:43
Closing since #185 tracks the relevant doc updates now.

**Closed by tylerbutler** 2016-03-27 16:43 UTC
