### ISSUE TITLE
PERFSTATS Discovery XML placeholder is not documented

### ISSUE THREAD

**Issue by fabiovazquez** [Microsoft/Office-Online-Test-Tools-and-Documentation#99] opened 2015-07-28 06:38 UTC
There is no documentation for the "PERFSTATS" placeholder in the "placeholder values" section:

http://wopi.readthedocs.org/en/latest/discovery.html#placeholder-values

**Comment by tylerbutler** [comment] 2015-07-28 13:38
Dupe of #52.

**Closed by tylerbutler** 2015-07-28 13:38 UTC
Labels: documentation, enhancement
