### ISSUE TITLE
WOPI Validation Service not sending POST requests

### ISSUE THREAD

**Issue by sermame** [Microsoft/Office-Online-Test-Tools-and-Documentation#244] opened 2016-07-20 14:54 UTC
While executing tests on WOPI Validation Service we are receiving GET requests only, including requests to PutFile operations.
Latest documentation states PutFile, PutRelativeFile, Lock, etc. as POST requests.

**Comment by tylerbutler** [comment] 2016-07-20 19:33
Can you double-check this? I cannot reproduce this behavior.

**Comment by sermame** [comment] 2016-07-21 06:55
Thanks for your response.
Validation Service continues sending GET Requests only.
We are using the Interactive WOPI Validation with the action set to "view".

**Comment by tylerbutler** [comment] 2016-07-21 07:07
I've tried repeatedly to reproduce this on our test host and can't. Can you please provide a Fiddler trace reproducing the behavior? From that I'll be able to look at our server logs to verify the requests were made properly.

**Comment by sermame** [comment] 2016-07-21 07:37
Using our test environment: http://esignabox.indenova.eu
that is our log for the "BaseWopi - PutUnlockedFile" test (No POST requests received):
```
[ajp-apr-8009-exec-3] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Proof: KHlKa7ctIrWvgYIZ98gke5SLpdQVNfggfQp84i1hmWZ1VO9BVH9Ygx1Re1QrpuJb5GspG/eULT04TkjKS0xJLPMk/VwBYpGa3hl5JbwknTfm5gfUGxlws4dAegAAjn0Jxt3clbZN85UsceGUujUsNU+ixy21YjduKEPXvPksk0s01vv7FTBi/sqgJ1vNyPVLIniibtU76EFVkrMOgyicbq4+CZNDzCo3MYMy6kwrkmEdUFRfb7ychS8tKVwv9A0ZJMmmNDCz6yegjPTp2eBn7kVEgRgYugENIwljJvKqJmP4G8ANmHAYe8YHuL6HcpCL9Geqrx2TGUFkuMAhMB5Glw==
X-WOPI-ProofOld: C1uWlPHBwkWZzr3woSKXTJrwkAtvMjZdj6AcQzPWeALuz2SLMHURiPa+PRr+aIks1ikx/9x248ENi0ydmtvTw98lBbvnzuG+j18faPt/7XrVipBCKhkQDsXcp8X8ME7BgojpMeS8SkJ+lBrSdQ4p7FO5V5Ds34GPbStIIK5Ti8iiwUwz34Muqg22m1bKeGDgJdPINZLxe5TWF7NG3AbVCwWSLAbVEb7zlUey861mVLcycDof8LlqWi8i27tjGEmRHNgpvJEqBoLZVbL7pYsIpmm5qv38pp8F+d1cTsQrSrmeAF1vYticGN+V4qZfqYuUleiEdFDchIyyicuwxSp/Tg==
X-WOPI-TimeStamp: 636046820493616661
host: esignabox.indenova.eu
connection: Keep-Alive
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


[ajp-apr-8009-exec-5] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Proof: vbX7JTdZAIM5EufrjhCMJGmVw+qXhhdKGyCsKncPczXJL3WVXvWMx+DI0uSokmX1SHCi5Saqf6r/n6T8hOS/X8xG+yaM2kJR3+NaX2HPkxQqr2MA2sTw46TJSyv4gSeCIGRBYfbfbSDarZZA/gI2iaMDWb71oLjrq6QiVzPeVe4g74Sdy74ndxJY7k+Py/6cXhPu1oi33hl8zVreXF7rHTx95QrQHNmUf/VLKKIna6Vy5Nqb5Zzh8FnnDtxnG4O4j2EaTzlUUKNFbCM567Pdrkxc5ZiZ+FIAYUkr/zo0gXMwp6SD4lH/s5FOujfVAPqC/Pp4n+5z5vK5RlDFG41sVA==
X-WOPI-ProofOld: l+n5Cp2mysu1LxwOaGRgiOnAo5GqsDKq1EN11TwZy/XuLvokL42+PCwz/aUvfomH0P3o80vqWdtcLfbKwCF/IdwexAy5pkrt2PxzxavcL5/KnctsMoUKxkF2pl4Jp4XIAW4t/sxVwvkO2E4ooA7XIWulPSI8rGePvY3iEM9hsJ9Na2MXxSOsu67MRtCCESmps3RQ/2NxbapzpOFgjwTzcygj4imYKRKYp9C/Y9C5HvPwD1cZZUyQxy2BEs5j6hxtcPAHUNNiJi7LdrmlihwWH0TqJon0gev69eE9WXTTfI8DaRM9FWghkeg8IOxVRz2ABQyQzwggfjcxD0IqIpGK2w==
X-WOPI-TimeStamp: 636046820506742394
host: esignabox.indenova.eu
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


[ajp-apr-8009-exec-6] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Lock: LockString
X-WOPI-Override: LOCK
X-WOPI-Proof: ERJc9rQ7qyqt4/HcBklBvaL9ZtGUjxz4du1IQVA+5dc4HZRCZU4JytB6qS6CPVV/QDQ64USwuj2MMtbh6EM9u6Ax5R048vnM7CR5eKJLWIlYTr0kH4taS0CvyAEWNW0uI+WsYCOqX5uvChDzt3BDU9xt30wIqBSlgcZ39NMFWBsdevgcH1unpTBL4uCUQKKvBZ4J5u2/k9AEAfhN5ChQG0TBpumHPCAZVn0R1aBdDjiSx46TLJpPlhUOwfgkleL+MCOSKC4ta0BxTr8paFIym/pmCV99k7eXsi+8VjG8XyUKFq/WnoJ+0BvsviJXtof6B7c9cv+A9Y3k5XOzPgWaXQ==
X-WOPI-ProofOld: RBBsyX1lyjOFjVD9550Hg7HkccCLbmXjh5tUxwHU1aem20YRtXT4ygcRewx1RdGNAAwjE6C4EBcwK4SlKp/w9lF+4lvkf5N35oWdy7kQY1n1LGKTb+GeIOWZ3Kd6IMWTOHAk4akMBnaD5FE9uMrPpF6i+4FzMjwIPuVNJEplXSN9pf/d5kq/oT+44ewh4AFv2goDiM5BbHKV5azNKBHAbk0/YneNFWghMKFIMFIRY6ZFaGkQQLR5xgEntgexM+d6BB56v77p90GPxhJywgM7MirOLVdqyeCDAw/pe/NfaOOrG+/V5yIwyW7TFB595xGgx5ZZnWjcCZmbMfIld9xnsw==
X-WOPI-TimeStamp: 636046820512680179
host: esignabox.indenova.eu
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


[ajp-apr-8009-exec-8] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862/contents
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Lock: LockString
X-WOPI-Override: PUT
X-WOPI-Proof: nOi2+LGof8e525fnfMSxaZh2ujM8MpYtHU5RGeGfh1hkfgDd4i6gkoVMwlcoIgxufnXxTU0bsx4b28fvkd/jH0/S7KitbbjnwHOq55H8t0EL+rWEVPi5pxH2XBmdTmAmojPDGXeZ5rzVDLTh5l3Ec6WKVnE287bP/Lz1FnjozHNatktSHJKgseqJaNnYzK6zdynzj6XhFaDKPY72Tk1kQ8xBf2O3rfYsX4AyMWBsGje0bERl4kRvqDSScLBrsNZXgX2fLwknPVLm8/+TPwgYkO6Kz1D6NQ0ksl15eEOya1oEi4jjYLPgyuq2I8rVV9T9DVlqburrd/2UM6hoNkAsbw==
X-WOPI-ProofOld: BJog81ooZSQ6AJgOS7zPSQi389zYMMrEPCptG/5JBYVe3i7i1A6HSAES3xIz6LffTSiTHRYN1+QTSbK4Uu1BPut341qfKRcrVf9L3Wn2Q6lWThFNb6icrrSTRLbg4O1navPfpTpf2+kKvhdsW6d/eTJGn1A001LcCJf1QoBeQk/bH5clJM/UlTb8e6cP+6sVnMj52jc0Bs2nWpuc3m8aaPBIVZ7NGjPHgECbMjzZYbGd1G2oi+gPjOfJOpZ4YVZioB9e5pM6NXQW9a4MRanb4tWf5ymRB38Zx3ZEvMu6ba+uwoZl+w/IzKds2LvkWrtzAb3lb1Il9ccq4PkxVMET8A==
X-WOPI-TimeStamp: 636046820518149002
host: esignabox.indenova.eu
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


[ajp-apr-8009-exec-7] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Lock: LockString
X-WOPI-Override: UNLOCK
X-WOPI-Proof: IMRhGFG1EVIZ1pwHtUwSZwZSHXNbcnqTHOHE+YsDHt2QzU7OrZZzZsEfcWt9JqBINZUh7gAfVydCT/j6rC75opQEAXjRhPzYQhN6WiA8BYap0Osx46MFj/3I1XzeGi6mNRaOwH+QpAp7jXcm6UfSU7ercS69giu/SjAmYpoPSXlbGYaJl8SkXJ11kU6YzVPhjDh5XUXNvQIMRK5p1kMgHhlVVxc6BVom/VB4QKjZbaH9UCxIzYRAOXHQnnBBx9ErStIhNf6P8C+Q/PpMuQf/Aru+gpErMMaT9ihz8n5D1wpfpN1CgCT7u464k8u7P/gu3/btXM6WMFj8tz2CZADrXg==
X-WOPI-ProofOld: m1+YO6B+xJz0/aoNuPJjcurWejFy8M2HNRZmDbInBTnzya8mlQpcOYp2koagZpNX0w8wbF1gMGwINXnviDPjVxjmgcjVIQtMUHtOX5T+1nfn4x27Rw1RWlW2lsbpaVsuM6Kavz4xZKhPLACvRBrF/4SnottSeh7KQi5xYV1S/U+Hx4Rdx/H49KSaWVYVosmH5gqO0i8ZEXs1zlrHbKM+R+CYA3X1NW4dJSVsv+GYPfvIgUaHampmSZnaKX/WtflsA2+EbusqwFXsQueZZKIxOfc1AohfIIqN88tuDDwJnUcI7O0RBDyv4xkFpjZL7hoIgUub90f5ZD0/QxTjN8YxOg==
X-WOPI-TimeStamp: 636046820523618010
host: esignabox.indenova.eu
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


[ajp-apr-8009-exec-9] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862/contents
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Override: PUT
X-WOPI-Proof: IO7v2nTx+7UNiil0yUivTNyU0cxQYOjG908/3aG5eViyT08R17RaGRk9Tdjw48BfMmctJ/gxoTZ019OtmqAYAJCLQkzvDPCcKgsvZN/25rKJjwSg8cc8hJi6+qXFMHVlnWHfGYJyDcwFuOXlCEE80qz0oTCMz/q0PTWlc4oFgyHvS3x7jofcuWW9SkvTE7wa9qnnRSvDzOoCZXf3PyaOb/JiANB31xtSvUtXrO3Oj3zg+6ZFgOgK/JTRleWmY0JBAs/Colw8CQRdiGJVZ4VOzYYhK26L72B8oDfMaw0yANy6mz8nZPCJm7FyrIQhb349OBFDz1SucJYui/QSD3bbsQ==
X-WOPI-ProofOld: n8Pu8UZwI+J+vqoPJi2MKDQHac3vKaXvvIHRmTxniuTXXHMaiRwCH5wECLhue9rye7HWtMaUtqV0I5Ff6cF8ALpGwg3s786KSMnjnYZmaflCWF9ga1gcnyVDGWqdLXHT32PZegBJPlSbJWcRNhoFvrb68+sdiu33EvmC38TYdJSaNlAtJcHD7lkZTwJ66H7/Tt3SBvQ1z9WlPuNlcb2h8hQCDjouwqMpnqJkeLfOY3y9V/cuKCAh8NHzAgb2v8faFK1uDm5ChHGVnOpF6ozakOqZtA95hIjiQdXbDUIU+xuNtKVx2kQqPKdDpqb5dmPSbVc1GiqF8dHLp85UtLTrdg==
X-WOPI-TimeStamp: 636046820529243416
host: esignabox.indenova.eu
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


[ajp-apr-8009-exec-10] INFO com.indenova.server.LoggingFilter - [metodo: doFilter] [linea: 96] -
------------------------------------------------------------------------
Method: GET
Endpoint: /TestOfficeOnline/wopi/v1/files/15862/contents
Query: access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811
Cookies:
Headers:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-WOPI-Proof: FlEEJthppLimzccUFi5YJJLw8ACPksC92l3FXR7ZgIN5Wl98swhNsBEzIMLMvyhn8xzaCJXgnzb5WAuQYmGGCqyi/JtAveFwSrOgY08+6/9WnPIj6qUifkiKJlsA81aZdWwt0A9ELvU4BsTbsOA4cDQIDv+7BAnGO0nmU9ZSNMdNUF3Xm8ixe9kQTXLtWFQenGUcB0h9ewk5nSZlLDH3XOuqU73DhDz6XZIOKBuqSZYIK/Js21D5yTvxf3anI0KrY7c7VZ8YRhpM2+KPvgGobMP5qRVDaD1nC12YbMqRx5E1mnUJ5LsRXmZE/jx0lGOLGq6z8PjNp8Ce/Ss4teu1tA==
X-WOPI-ProofOld: nV+35oyfT9rHwLMX9bY8nHVFuEsiWRREbK4rmyvkF+gG5igBgrNLPWNu+IAGOosGOSptvbBe/ibpQL6ioGa4SWoDGUwjt61vusjBXoCTYvHIFm7keECFizkV8sagxKQfnBjFETasD+CSMsqQ/S5FkFu299El9ypJuQf97gCEP64wXGkbXoVOhx0gXLMFjXNJqOcdPo17UTWwYhpq/OkPQAxfG4i+HNqGMYtjI9qzG3kGvTO6yIw/rGzNnFU/e/HiaQg2F45QCRqB1DlT2fwYaewIaU/9wNQp/B/ypyCXriLLLr27Fft25K+L2eE1NRynGgH5NLoKKdVMV73R0mjRNw==
X-WOPI-TimeStamp: 636046820534868599
host: esignabox.indenova.eu
Parameters:
access_token_ttl: 1469086430811
access_token: gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E/JUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5+4YiuqYL2X1PmJLaKb5WQ8=
Body:


```

And this is our Tomcat access log:
```
13.91.4.123 - - [21/Jul/2016:09:17:29 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 560

13.91.4.123 - - [21/Jul/2016:09:17:30 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 560

13.91.4.123 - - [21/Jul/2016:09:17:30 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 560

13.91.4.123 - - [21/Jul/2016:09:17:31 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862/contents?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 -

13.91.4.123 - - [21/Jul/2016:09:17:32 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 560

13.91.4.123 - - [21/Jul/2016:09:17:32 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862/contents?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 -

13.91.4.123 - - [21/Jul/2016:09:17:33 +0200] "GET /TestOfficeOnline/wopi/v1/files/15862/contents?access_token=gpVnLe4HopLWs3OHsJAye6ShN7dq2PvC4aXZraMQemCoegbMZiUoSesm4yIB9ymRDUgDIOXNJSTzLPWTJlWAKkQYQdYp6tKaw67eXQyi8YQMjxxnhJOmGz2Lg2VrFsOlBf26eR8E%2FJUqq7wy8Gk5UfERJ6ZRnz6uQxxwrhCU8gfA6nUwW5m2caBIVd72yc1DWyMJ5%2B4YiuqYL2X1PmJLaKb5WQ8%3D&access_token_ttl=1469086430811 HTTP/1.1" 200 -
```

**Comment by sermame** [comment] 2016-07-21 08:13
Well, this is awkward, but it seems that our front Apache was redirecting all requests from http to https changing the request method to GET.  By sending correctly the WOPISrc param everything seems to be ok.
Thanks for your help and sorry for the inconvenience.

**Comment by tylerbutler** [comment] 2016-07-21 16:23
Closing since this was an issue on the partner side.

**Closed by tylerbutler** 2016-07-21 16:23 UTC
