### ISSUE TITLE
 implenment of Co-authoring in word through wopi rest

### ISSUE THREAD

**Issue by sicexpn** [Microsoft/Office-Online-Test-Tools-and-Documentation#265] opened 2016-09-29 10:33 UTC
I achieve the excel and ppt in co-authoring ,but word not work, which need to control lock. How can I do?

**Comment by vir2610** [comment] 2016-09-29 12:27
There is no separate mechanism to achieve co-authoring for individual formats mate !! 
Have you tested WOPI validator passed with all tests related to Office Online? If not yet, then please start from there.
Unfortunately I am facing the same issue even if I have passed all the I have passed all the tests for the same.
If you any resolution on this in near by future then please let me know !!

**Comment by tylerbutler** [comment] 2016-09-29 15:56
The most likely explanation for ao-authoring not working in Word is that you're not properly responding to Lock requests with a 409 when the lock ID passed in the request doesn't match the current lock on the file.

As @vir2610 mentioned, you should first check that your WOPI validator tests are passing. In particular, the tests in the Lock category are important.

**Comment by sicexpn** [comment] 2016-09-30 02:14
Hello, @tylerbutler the header of "X-WOPI-Lock" is  {"S":"52510d33-5acf-4a59-a585-85b7f8417e60","F":6,"E":2,"M":"102dc8840fc741fd96855402f58c633a","P":"39C1376D-8651-42C8-B19D-C46B93E75CA2"}, what the meaning of "S"、"F"、"E"、"M"、"P" ？, when responding to Lock requests with a 409 when the lock ID（I use the "S" field)， the result is that the word is allowed one user to edit. How can I do？Thanks

**Comment by tylerbutler** [comment] 2016-09-30 15:36
@sicexpn In a previous comment you mentioned that you were parsing the lock ID. Don't do that. Lock ID string are opaque to the WOPI host. You shouldn't be parsing them or doing anything to them. All you need to do is compare the lock strings as strings.

From [the docs](https://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-lock):

> ...hosts do not need any knowledge or understanding of the contents of the lock ID. **Hosts must treat it as an opaque string.**

Also, the [SupportsCoauth](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/CheckFileInfo.html#term-supportscoauth) property has no effect in Office Online. It is listed in the _Deprecated properties_ section of the documentation. If co-authoring is now working for you, it is likely because you fixed your lock handling.

**Comment by tylerbutler** [comment] 2016-11-02 12:24
I assume this is resolved, so closing. Please reopen this issue with more details if you need further help.

**Closed by tylerbutler** 2016-11-02 12:24 UTC
Labels: help wanted

**Comment by SevenYears** [comment] 2017-04-24 07:52
I am facing the same issue ，I achieve the excel and ppt in co-authoring ,but word not work！
If it is a lock problem，and how to respond to Lock requests with a 409 when the lock ID passed in the request doesn't match the current lock on the file? 
Thanks

**Comment by tylerbutler** [comment] 2017-04-24 14:46
@SevenYears You need to compare the lock ID passed on a lock request and if it doesn't match with the current lock on the file, you return a 409 and include the lock ID on your response. See these sections of the documentation for more details:

* https://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-lock
* https://wopi.readthedocs.io/projects/wopirest/en/latest/files/Lock.html

The [WOPI validator](https://wopi.readthedocs.io/en/latest/build_test_ship/validator.html) also includes tests that help verify you're correctly handling lock-related requests.

If you still need help, please file a new issue and follow [our troubleshooting guide](https://wopi.readthedocs.io/en/latest/build_test_ship/troubleshooting.html) when reporting issues.

**Comment by Gelembjuk** [comment] 2018-02-16 11:02
Hi All,
I try to integrate co-authoring and have no success .
I can make 2 users to open a document. But i don't see any sync of their updates. Each sees only own updates and putfile only saves separate updates of each user.

What i did for co-authoring : for second user CheckFileInfo returns success, same response as for the first opened user.
{"BaseFileName":"18.docx","OwnerId":"150273","UserId":"150273","Size":"34508","Version":"2329419c10adef5ea30a898cf9140fa9","UserCanWrite":true,"WebEditingDisabled":false,"RestrictedWebViewOnly":false,"ReadOnly":false,"SupportsUpdate":true,"SupportsLocks":true,"SupportsCoauth":false,"SupportsCobalt":false,"SupportsFolders":false,"SupportsScenarioLinks":false,"SupportsSecureStore":true}

Then the LOCK request for the second user returns success. I sow some comments that it should return 409 conflict with lock of a first user. But when i do this the second user sees error "You can not edit with other users now".
If i return success on his lock then he can see document. 
But no any co-authoring.

What can be the problem?

**Comment by tylerbutler** [comment] 2018-02-16 14:17
@Gelembjuk Please move this question and discussion to the [CSPP Yammer group](https://www.yammer.com/officeenterprisenda/#/threads/inGroup?type=in_group&feedId=7197423), which is a better place for help on implementation issues (as opposed to documentation issues, which this repo tracks).

What you're seeing implies you're not handling locks properly, and the [WOPI validator](https://wopi.readthedocs.io/en/latest/build_test_ship/validator.html) includes tests that help verify you're correctly handling lock-related requests. Start with it and ensure all the lock tests are passing.

**Comment by lion3311** [comment] 2019-08-25 13:52
Hi all,
I have implemented WOPI using asp.net core 2.2 and all docx view and co-authoring work fine. 
When second user try to edit the file return 409 conflict result with Response of current lock.

The problem is it causes session expired issue(sometimes).  when i return ok result session issue is not come but co-authoring not work. Is there any solution for session expired issue.

**Comment by tylerbutler** [comment] 2019-08-25 17:38
@lion3311 Please move this question and discussion to the [CSPP Yammer group](https://www.yammer.com/officeenterprisenda/#/threads/inGroup?type=in_group&feedId=7197423), which is a better place for help on implementation issues (as opposed to documentation issues, which this repo tracks).
